# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  #pull_request:
    #branches: [ "main" ]
env:
  version: ${{ case(github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name,'v'), github.ref_name, format('v{0}.{1}.{2}.{3}',0,0,github.run_number,github.run_attempt)) }}
jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"] #, "3.11"]
    steps:
    - uses: actions/checkout@v4
      with:
        path: wkapp
    - name: "Set version ${{ env.version }}"
      run: |
        VERSION='${{ env.version }}'
        VERSION="${VERSION/v/}"
        sed -ie "s/__version__.*'/__version__ = '${VERSION}'/" wkapp/__init__.py
        cat wkapp/__init__.py | head
        sed -ie "s/__version__.*'/__version__ = '${VERSION}'/" wkapp/wkapp.py
        cat wkapp/wkapp.py | head   				
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install pythonista-stubs
        if [ -f wkapp/requirements.txt ]; then pip install -r wkapp/requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd wkapp
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Test with pytest
#      run: |
#        pytest
    - name: Build
      run: |
        cp wkapp/pyproject.toml pyproject.toml
        cp wkapp/README.md README.md
        cp wkapp/LICENSE LICENSE
        python -m pip install --upgrade build
        python -m pip install --upgrade flit
        python -m pip install --upgrade pythonista-stubs
        python -m build
    - name: Store package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: dist
  test-pypi-publish:
    needs: build
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write
    steps:
      - name: Retrieve package artifacts
        uses: actions/download-artifact@v5
        with:
          name: packages
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip-existing: true
  pypi-publish:
    needs: build
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name,'v') }}
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Retrieve package artifacts
        uses: actions/download-artifact@v5
        with:
          name: packages
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true